### ISSUE TITLE
[Tuist] 프로젝트 구조 변경해보기

### ISSUE THREAD

**Issue by butter-free** [OpenStudies/OpenAppStore#4]
현재 저희 프로젝트 구조를 아래와같이 한번 변경 해보세요!

App: 메인 앱 프로젝트
Home: 홈 화면이 포함될 프로젝트
Application: 앱 리스트 정보 화면이 포함될 프로젝트
Search: 검색 리스트 화면이 포함될 프로젝트

* App은 app product로 구성
* Home, Application, Search는 product를 static framework로 구성

<img width="291" alt="스크린샷 2022-10-01 오전 8 43 23" src="https://user-images.githubusercontent.com/24970070/193369824-8c6805fe-d4a8-4247-b3cf-3768894e8305.png">

**Comment by tyson10** [comment]
질문이 있습니다

1. tuist generate 하니까 폴더 안 만들어놓고 못찾는다길래 각 프로젝트 내부에 폴더를 직접 수동으로 만들었는데 그게 맞나요?(Sources, Resources...)
2. Sources, Resources 등의 폴더를 만들고 생성에 성공했는데 막상 프로젝트 열어보면 안보이는데 이게 정상인가요?

**Comment by butter-free** [comment]
1. 맞아요! 폴더기반으로 tuist가 읽어서 프로젝트를 생성해주기 때문에 수동생성 해야 합니다.

2. 폴더내에 내용물이 없어서 안보일꺼에요 필요하다면 empty.txt 같은 더미파일 만들어서 넣어두곤 합니다
